project:
  type: website
  output-dir: docs
  preview: 
    # port: 5556
    # browser: true
    # watch-inputs: true
    navigate: true

website:
  title: "Shingo Nitta"
  # favicon: "{{< fluent animal-turtle-20-regular >}}"
  # site-url: https://shingonitta.com
  # repo-url: https://github.com/ningositta/ningositta.github.io


  navbar:
    left:
      - href: index.qmd
        text: "HOME"
      - text: "PROFILE"
        file: profile/index.qmd
      - text: "RESEARCH"
        file: research/index.qmd
      - text: "NOTES"
        file: notes/index.qmd

# {{< iconify material-symbols home-outline >}}

format:
  html:
    theme: 
      light: [simplex, format/custom.scss]
    mainfont: 'M PLUS 1P'
